production:
  expire_requested_chat_sessions:
    class: ExpireRequestedChatSessionsJob
    schedule: every minute
  sync_active_chat_sessions:
    class: SyncActiveChatSessionsJob
    schedule: every minute
