production:
  expire_requested_chat_sessions:
    class: ExpireRequestedChatSessionsJob
    schedule: every minute
  sync_active_chat_sessions:
    class: SyncActiveChatSessionsJob
    schedule: every minute
  sync_active_calls:
    class: SyncActiveCallsJob
    schedule: every 30 seconds
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: "12 * * * *"
  clear_solid_queue_finished_batches:
    command: "SolidQueue::Batch.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: "42 * * * *"
  cleanup_operational_logs:
    class: CleanupOperationalLogsJob
    schedule: every day at midnight
